### ISSUE TITLE
Cmds to install app via git on ubuntu

### ISSUE THREAD

**Issue by johnfelipe** [splitt3r/mindmaps#10]
i want to know steps and commands cheatsheet style for ubuntu 16
Stay alert

**Comment by splitt3r** [comment]
https://github.com/splitt3r/mindmaps#install-from-git should be enough. Do you encounter any problems?

**Comment by splitt3r** [comment]
I think this can be closed. If there are any problems left don´t hesitate to reopen / comment here.
