### ISSUE TITLE
Frontend rework with Vue.js + TypeScript

### ISSUE THREAD

**Issue by splitt3r** [splitt3r/mindmaps#3]
As https://scrutinizer-ci.com/g/splitt3r/mindmaps/code-structure/master/js-file/js%2Fview%2FView.js shows the js view is way to complex and to big. This needs an complete overhaul and a switch to Vue.js.

- [X] Create / Edit / Delete mindmap
- [X] Create / Edit / Delete mindmap node
- [X] Change description
- [x] Show description update msg
- [X] Sharing
  - [X] Basic sharing #2
  - [X] Show full user / group / circle name instead of the id
- [X] Delete child nodes
- [X] Delete mindmaps on user deletion
- [x] The mindmap should use all available space and resize with the browser window
- [x] Reload (only changes) mindmaps / nodes to stay up to date

See: https://github.com/ChristophWurst/nextcloud_vue & https://github.com/owncloud/market

**Comment by splitt3r** [comment]
@skjnldsv any idea how to add the blue border here? I´m using the inputs in a popover and copied some of your css but the border on hover is missing on the right sight of the text input.

How it looks like:

![border](https://user-images.githubusercontent.com/1869584/34618185-3a7f1558-f23e-11e7-9c3f-999651621886.png)

How it should look like:

![border](https://user-images.githubusercontent.com/1869584/34618210-52497e8a-f23e-11e7-81a6-5ba1aaded152.png)

**Comment by skjnldsv** [comment]
@splitt3r I don't remember, is the inputs in popover standard pushed into master?
I was working on something like that on #7600, so it might require some fixes. This is a css zindex issue, can and need a small fix in master! :)

**Comment by splitt3r** [comment]
Thanks for the quick reply :) it´s https://github.com/splitt3r/mindmaps/blob/feature/rework-js/js/components/MindmapView.vue#L28-L32 with https://github.com/splitt3r/mindmaps/blob/feature/rework-js/js/components/MindmapView.vue#L241-L283
