### ISSUE TITLE
Cannot locate in Nextcloud 13 appstore

### ISSUE THREAD

**Issue by sunjam** [splitt3r/mindmaps#38]
Hi, I cannot locate Mindmaps in the actual Nextcloud 13 appstore under _Tools,_ as shown on[ the app website](https://apps.nextcloud.com/apps/mindmaps).  Also, would you please add the app to multiple appstore categories such as:  _Tools,_  _Office & text,_ and _Organization_.

**Comment by splitt3r** [comment]
This app is still a nightly version but the appstore only shows them in the web ui. You have to download the app zip and upload it to your apps folder manually for now. I will add further categories to the app :) sounds like a good idea.
