### ISSUE TITLE
How To Install on Snap Version of NextCloud

### ISSUE THREAD

**Issue by stone212** [splitt3r/mindmaps#53]
This is not a bug.  I am just looking for installation instructions for MindMaps when the NextCloud installation is on Snap.

Is there a doc somewhere I can read?  I looked but I could not find it.

**Comment by splitt3r** [comment]
It should be the same way as for normal installations. Which version of Nc is installed as a snap?

**Comment by stone212** [comment]
@splitt3r Version 12.  But the snap filesystem is not writeable by default.  This is my first snap, which is why I'm hoping for a doc.  I'll learn as much about Snaps as about mindmaps.

**Comment by splitt3r** [comment]
This app requires Nc 13 so that´s the problem.

**Comment by stone212** [comment]
> This app requires Nc 13 so that´s the problem.

No that isn't the problem.  I never got to the point where that was the problem. :)  Please give the instructions for upgrading on the v13 *snap* not the other installs of NextCloud. The snap will automatically upgrade to v 13 sometime soon (the code is being released around now).  Then how do I install this mindmaps?

**Comment by stone212** [comment]
@splitt3r From the nextcloud-snap team: 

> Indeed, the snap itself is not writable, so when you install apps they go into a writable area, specifically the /var/snap/nextcloud/current/nextcloud/extra-apps/ directory. Try manually extracting apps there.

**Comment by splitt3r** [comment]
I saw a tweet yesterday that v13.0.2 was realeased as a snap.

**Comment by stone212** [comment]
@splitt3r Yeah I think it automatically upgraded.  It wasn't obvious because the "Help" page still brings up docs for v12.  But I have just now tried the method I posted above and Mind Maps is working!
