### ISSUE TITLE
What's the difference between this and the other Mindmap NextCloud app?

### ISSUE THREAD

**Issue by jcklpe** [splitt3r/mindmaps#66]
Why are there two apps both named mind map in the nextcloud store? I don't understand how they differ in functionality but if nothing else it seems that there should be some better naming scheme to tell them apart.

**Comment by DBJRdev** [comment]
I'm not affiliated to any of the apps, but I can share our experience: this app here seems to be very rudimental whereas the other one seems to be already advanced, yet in our testing we only saw a Chinese user interface – so it was also not that useful to us yet.

**Comment by splitt3r** [comment]
There is another one :flushed: will check that.

**Comment by jcklpe** [comment]
@splitt3r  Yeah, you can check my mirror question on their app here: https://github.com/ACTom/files_mindmap/issues/1#issuecomment-430115820

Also I'll make the same offer to help with any branding design you might need 😄  https://github.com/jcklpe/Open-Source-Branding/issues/new

I'm new to Open Source and I'm still a very junior dev, so I'm hoping I can help use my design skills to help people out!

**Comment by rubo77** [comment]
This mind map app adds a new icon to the top which is only about mind mapping.

 the other one is not visible at first it just allows you to edit mind Maps inside the files application

**Comment by rubo77** [comment]
I helped with internationalisation, so it is a bit less Chinese-only with version 0.0.7

**Comment by jcklpe** [comment]
@rubo77  Excellent!

Also updated my Open Source Branding project with a new template to help clarify the process for people who want to request stuff: https://github.com/jcklpe/Open-Source-Branding/issues/new?template=branding-request.md

**Comment by splitt3r** [comment]
@jcklpe sounds great 👍. Once i find the time to fix the issues i will also investigate the possible merge with the other mindmaps app.
