### ISSUE TITLE
edit/sync with any native clients IOs/Android

### ISSUE THREAD

**Issue by LuxoftAKutsan** [splitt3r/mindmaps#71]
Is there a functionality to modify created by this app files with any native app on mobile/tab?
I have Ipad and i would like to use Nextcloud mindmaps on it! But I dont see ability to export generated files to any MindMap ios app, or add next cloud as external storage with ability to modify this file format.

**Comment by splitt3r** [comment]
No there is none yet and the app isn´t under active development anymore.

**Comment by LuxoftAKutsan** [comment]
@splitt3r thanks for the response. Is there any clone of mindmaps for nextcloud? 
Or app is just dead and nobody wan't it any more?

**Comment by splitt3r** [comment]
https://apps.nextcloud.com/apps/files_mindmap looks way more feature rich :) but sadly you can not migrate your mindmaps.
